- name: harden_node
  hosts: harden_hosts
  vars_files:
    - ~/harden/vars/external_vars.yml
  roles:  
    - users
    - pkgs
    - fips
    - fstab
    - dconf
    - aide
    - auditd
    - ssh
    - grub
    - misc

  handlers:
    - name: restart_sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
    - name: restart_dconf
      ansible.builtin.command: dconf update
    - name: aide_init
      ansible.builtin.command: /usr/sbin/aide --init
    - name: update_grub
      ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
