---
- name: copy_aide_conf
  ansible.builtin.copy:
    src: "{{ role_path }}/files/aide.conf"
    dest: /etc/aide.conf
    owner: root
    group: root
    mode: '0600'

- name: copy_aide_cronjob
  ansible.builtin.copy:
    src: "{{ role_path }}/files/aide"
    dest: /etc/cron.daily/aide
    owner: root
    group: root
    mode: '0600'
  notify: aide_init
