---
- name: copy_dconf_local_d_settings
  ansible.builtin.copy:
    src: "{{ role_path }}/files/local.d/00-security-settings"
    dest: /etc/dconf/db/local.d/00-security-settings
    owner: root
    group: root
    mode: '0640'

- name: copy_dconf_distro_d_settings
  ansible.builtin.copy:
    src: "{{ role_path }}/files/distro.d/00-security-settings"
    dest: /etc/dconf/db/distro.d/00-security-settings
    owner: root
    group: root
    mode: '0640'
  notify: restart_dconf  
