- name: add_etc_issue
  ansible.builtin.copy:
    src: "{{ etc_issue_file }}"
    dest: /etc/issue
    owner: root
    group: root
    mode: '0640'

- name: symlink_etc_issue
  ansible.builtin.file:
    src: /etc/issue
    dest: /etc/issue.net
    owner: root
    group: root
    state: link
    force: true

- name: add_compliance_updates_conf
  ansible.builtin.copy:
    src: "{{ sshd_compliance_updates_conf_file }}"
    dest: /etc/ssh/sshd_config.d/00-compliance-updates.conf
    owner: root
    group: root
    mode: '0640'
  notify: restart_sshd
