- name: add_etc_issue
  ansible.builtin.copy:
    src: "{{ role_path }}/files/issue"
    dest: /etc/issue
    owner: root
    group: root
    mode: '0640'

- name: symlink_etc_issue
  ansible.builtin.file:
    src: /etc/issue
    dest: /etc/issue.net
    owner: root
    group: root
    state: link
    force: true

- name: remove_dup_options
  ansible.builtin.copy:
    src: "{{ role_path }}/files/50-redhat.conf"
    dest: /etc/ssh/sshd_config.d/50-redhat.conf
    owner: root
    group: root
    mode: '0600'
  when: ansible_facts.distribution_major_version == "9"

- name: update_ssh_crypto_policy
  ansible.builtin.lineinfile:
    path: /usr/share/crypto-policies/FIPS/openssh.txt
    regex: '^Ciphers aes256-gcm@openssh.com,aes256-ctr,aes128-gcm@openssh.com,aes128-ctr'
    line: 'Ciphers aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes128-gcm@openssh.com,aes128-ctr'

- name: update_sshserver_crypto_policy
  ansible.builtin.lineinfile:
    path: /usr/share/crypto-policies/FIPS/opensshserver.txt
    regex: '^Ciphers aes256-gcm@openssh.com,aes256-ctr,aes128-gcm@openssh.com,aes128-ctr'
    line: '^Ciphers aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes128-g cm@openssh.com,aes128-ctr'

- name: add_compliance_updates_conf
  ansible.builtin.copy:
    src: "{{ role_path }}/files/00-compliance-updates.conf"
    dest: /etc/ssh/sshd_config.d/00-compliance-updates.conf
    owner: root
    group: root
    mode: '0640'
  when: ansible_facts.distribution_major_version == "9"
  notify: restart_sshd

- name: add_sshd_conf
  ansible.builtin.copy:
    src: "{{ role_path }}/files/sshd_config"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  when: ansible_facts.distribution_major_version == "8"
  notify: restart_sshd
