---
- name: copy_audit_dot_rules
  ansible.builtin.copy:
    src: "{{ role_path }}/files/audit.rules"
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: '0600'

- name: copy_auditd_conf
  ansible.builtin.copy:
    src: "{{ role_path }}/files/auditd.conf"
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: '0640'

- name: update_audit_plugin_syslog_conf
  ansible.builtin.lineinfile:
    path: /etc/audit/plugins.d/syslog.conf
    regex: '^active ='
    line: active = yes
