- name: copy_file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/foofile8"
    dest: /tmp/foofile8
  when: ansible_facts.distribution_major_version == "8"

- name: mask_debug_shell
  ansible.builtin.systemd_service:
    name: debug-shell
    enabled: false
    masked: true
