- name: add_modprobe_options
  ansible.builtin.copy:
    src: "{{ role_path }}/files/disabled_modules.conf"
    dest: /etc/modprobe.d/disabled_modules.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts.distribution_major_version == "9"
