- name: remove_at_deny
  ansible.builtin.file:
    path: /etc/at.deny
    state: absent

- name: remove_cron_deny
  ansible.builtin.file:
    path: /etc/cron.deny
    state: absent

- name: add_cron_allow
  ansible.builtin.file:
    path: /etc/cron.allow
    state: touch
    owner: root
    group: root
    mode: '0600'

- name: mask_avahi_daemon
  ansible.builtin.systemd_service:
    name: avahi-daemon.service
    enabled: false
    masked: true

- name: mask_bluetooth_server
  ansible.builtin.systemd_service:
    name: bluetooth.service
    enabled: false
    masked: true

- name: mask_debug_shell
  ansible.builtin.systemd_service:
    name: debug-shell.service
    enabled: false
    masked: true

- name: mask_kdump
  ansible.builtin.systemd_service:
    name: kdump.service
    enabled: false
    masked: true

- name: mask_coredump
  ansible.builtin.systemd_service:
    name: systemd-coredump.socket
    enabled: false
    masked: true

- name: add_limits
  ansible.builtin.copy:
    dest: /etc/security/limits.d/other_limits.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      * hard maxlogins 10
      * hard core 0

- name: add_disa_options
  ansible.builtin.copy:
    dest: /etc/profile.d/disa_options.sh
    owner: root
    group: root
    mode: '0644'
    content: |
      typeset -xr TMOUT=600
      umask 077

- name: update_pwquality_conf
  ansible.builtin.blockinfile:
    path: /etc/security/pwquality.conf
    block: |
      difok = 8
      minlen = 15
      dcredit = -1
      ucredit = -1
      lcredit = -1
      ocredit = -1
      minclass = 4
      maxrepeat = 3
      maxclassrepeat = 4
      dictcheck = 1
      enforce_for_root
      retry = 3

- name: update_pwhistory_conf
  ansible.builtin.blockinfile:
    path: /etc/security/pwhistory.conf
    block: |
      remember = 24

- name: update_faillock_conf
  ansible.builtin.blockinfile:
    path: /etc/security/faillock.conf
    block: |
      deny = 3
      even_deny_root
      dir = /var/log/faillock
      fail_interval = 900
      unlock_time = 0

- name: add_ctrl_alt_delete_action
  ansible.builtin.blockinfile:
    path: /etc/systemd/system.conf
    block: |
      CtrlAltDelBurstAction=none

- name: add_journald_options
  ansible.builtin.blockinfile:
    path: /etc/systemd/journald.conf
    block: |
      Compress=yes
      Storage=persistent

- name: symlink_ctrl_alt_delete
  ansible.builtin.file:
    src: /dev/null
    dest: /etc/systemd/system/ctrl-alt-del.target
    owner: root
    group: root
    state: link
    force: true

- name: update_useradd
  ansible.builtin.replace:
    path: /etc/default/useradd
    regexp: 'INACTIVE=-1'
    replace: 'INACTIVE=35'

- name: update_coredump
  ansible.builtin.replace:
    path: /etc/systemd/coredump.conf
    regexp: '#Storage=external'
    replace: 'Storage=none'

- name: update_pass_min
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regex: '^PASS_MIN_DAYS\s+'
    line: 'PASS_MIN_DAYS 1'

- name: update_pass_max
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regex: '^PASS_MAX_DAYS\s+'
    line: 'PASS_MAX_DAYS 60'

- name: update_fail_delay
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regex: '^#FAIL_DELAY\s+'
    line: 'FAIL_DELAY 4'

- name: update_login_defs_umask
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regex: '^UMASK\s+'
    line: 'UMASK 077'

- name: update_bashrc_umask
  ansible.builtin.replace:
    path: /etc/bashrc
    regexp: '022'
    replace: '077'

- name: update_cshrc_umask
  ansible.builtin.replace:
    path: /etc/csh.cshrc
    regexp: '022'
    replace: '077'

# remove rescue from /usr/lib/systemd/system/rescue.service
